spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        - id: minitereEF
          uri: lb://ministereef
          predicates:
            - Path=/ministereef/**
        - id: m_interieur
          uri: lb://m_interieur
          predicates:
            - Path=/m_interieur/**

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true
    instance:
      hostname: localhost

server:
  port: 8989